core:
    resource: "@CoreBundle/Resources/config/routing_oauth.yml"
    prefix:   /

    
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /



front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /
    
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

coreextra:
    resource: "@CoreExtraBundle/Controller/"
    type:     annotation
    prefix:   / 